- name: Check if docker-compose.yml exists
  stat:
    path: /monitoring/docker-compose.yml
  register: compose_file

- name: Run Docker Compose Down
  shell: sudo docker compose down
  args:
    chdir: /monitoring
  when: compose_file.stat.exists

- name: Remove monitoring directory
  file:
    path: /monitoring                
    state: absent

- name: Create directory monitoring  
  file:
    path: /monitoring       
    state: directory
    mode: '0755'

- name: Copy . directory
  copy:
    src: .
    dest: /monitoring  

- name: Run Docker Compose Up
  shell: sudo docker compose up -d
  args:
    chdir: /monitoring