version: '3.8'

services:
  rabbitmq:
    image: "rabbitmq:3.9-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 30s
      timeout: 10s
      retries: 5
      
  dramatiq:
    build: .
    command: ["sh", "-c", "while ! nc -z rabbitmq 5672; do sleep 1; done; dramatiq tasks"]
    depends_on:
      rabbitmq:
        condition: service_healthy

  scheduler:
    build: .
    command: ["sh", "-c", "while ! nc -z rabbitmq 5672; do sleep 1; done; python scheduler.py"]
    environment:
      - IPS=192.168.144.133,192.168.144.135,192.168.144.137
      - FLASK_API_URL=http://192.168.144.1:5000/run_playbook
    depends_on:
      rabbitmq:
        condition: service_healthy