# - name: Cập nhật cache APT và cài đặt PgBouncer
#   ansible.builtin.apt:
#     name: pgbouncer
#     state: present
#     update_cache: yes

# - name: Tạo nhóm 'pgbouncer' nếu chưa tồn tại
#   group:
#     name: "{{ pgbouncer_group }}"
#     state: present

# - name: Tạo user và group cho pgbouncer
#   user:
#     name: "{{ pgbouncer_user }}"
#     group: "{{ pgbouncer_group }}"
#     createhome: yes

# - name: Tạo thư mục cấu hình PgBouncer
#   ansible.builtin.file:
#     path: "{{ pgbouncer_conf_dir }}"
#     state: directory
#     owner: "{{ pgbouncer_user }}"
#     group: "{{ pgbouncer_group }}"
#     mode: '0755'

# - name: Tạo thư mục logs PgBouncer
#   ansible.builtin.file:
#     path: "{{ pgbouncer_log_dir }}"
#     state: directory
#     owner: "{{ pgbouncer_user }}"
#     group: "{{ pgbouncer_group }}"
#     mode: '0755'

# - name: Tạo tệp cấu hình PgBouncer
#   ansible.builtin.template:
#     src: pgbouncer.ini.j2
#     dest: "{{ pgbouncer_conf_dir }}/pgbouncer.ini"
#     owner: "{{ pgbouncer_user }}"
#     group: "{{ pgbouncer_group }}"
#     mode: '0644'

# - name: Tạo tệp userlist
#   ansible.builtin.template:
#     src: userlist.txt.j2
#     dest: "{{ pgbouncer_conf_dir }}/userlist.txt"
#     owner: "{{ pgbouncer_user }}"
#     group: "{{ pgbouncer_group }}"
#     mode: '0640'
#   notify: restart pgbouncer


- name: Check if docker-compose.yml exists
  stat:
    path: /vdt_pgbouncer/docker-compose.yml
  register: compose_file

- name: Run Docker Compose Down
  shell: sudo docker compose down
  args:
    chdir: /vdt_pgbouncer
  when: compose_file.stat.exists
    
- name: Remove directory vdt
  file:
    path: /vdt_pgbouncer           
    state: absent

- name: Create directory vdt_pgbouncer  
  file:
    path: /vdt_pgbouncer       
    state: directory
    mode: '0755'

- name: Render Docker Compose template
  template:
    src: docker-compose.yml.j2
    dest: /vdt_pgbouncer/docker-compose.yml

- name: Render pgbouncer.ini template
  template:
    src: pgbouncer.ini.j2
    dest: /vdt_pgbouncer/pgbouncer.ini

- name: Render userlist template
  template:
    src: userlist.txt.j2
    dest: /vdt_pgbouncer/userlist.txt

- name: Run Docker Compose Up
  shell: sudo docker compose up -d
  args:
    chdir: /vdt_pgbouncer