apiVersion: v1
kind: Service
metadata:
  name: haproxy
  namespace: default
spec:
  type: NodePort
  ports:
    - name: primary-port
      port: 5000
      targetPort: 5000
      nodePort: 31000 
    - name: replicas-port
      port: 5001
      targetPort: 5001
      nodePort: 31001
    - name: stats-port
      port: 7000
      targetPort: 7000
      nodePort: 31007
  selector:
    app: haproxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
      - name: haproxy
        image: haproxy:2.4
        ports:
        - containerPort: 5000
        - containerPort: 5001
        - containerPort: 7000
        volumeMounts:
        - name: haproxy-config
          mountPath: /usr/local/etc/haproxy/haproxy.cfg
          subPath: haproxy.cfg
      volumes:
      - name: haproxy-config
        configMap:
          name: haproxy-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: haproxy-config
  namespace: default
data:
  haproxy.cfg: |
    global
      maxconn 100

    defaults
      log  global
      mode tcp
      retries 2
      timeout client 30m
      timeout connect 4s
      timeout server 30m
      timeout check 5s

    listen stats
      mode http
      bind *:7000
      stats enable
      stats uri /

    listen primary
      bind *:5000
      server patroni-0 patronidemo:5432 check
      
    listen replicas
      bind *:5001
      server patroni-repl patronidemo-repl:5432 check