---
- name: Check if docker-compose.yml exists
  stat:
    path: /home/vinh/myhaproxy/docker-compose.yaml
  register: compose_file

- name: Run Docker Compose Down
  shell: docker compose down
  args:
    chdir: /home/vinh/myhaproxy
  when: compose_file.stat.exists
    
- name: Remove directory myhaproxy
  file:
    path: /home/vinh/myhaproxy           
    state: absent

- name: Create directory myhaproxy  
  file:
    path: /home/vinh/myhaproxy       
    state: directory
    mode: '0755'

- name: Copy . directory
  copy:
    src: .
    dest: /home/vinh/myhaproxy

- name: Render entrypoint.sh
  template:
    src: entrypoint.sh.j2
    dest: /home/vinh/myhaproxy/entrypoint.sh
    mode: '0755'

# - name: Render haproxy.toml
#   template:
#     src: conf.d/haproxy.toml.j2
#     dest: /home/vinh/myhaproxy/conf.d/haproxy.toml

- name: Run Docker Compose Up
  shell: docker compose up -d
  args:
    chdir: /home/vinh/myhaproxy