version: '3'

services:
  db:
    image: postgres
    ports:
      - 5433:5432
    volumes:
      - postgresdb3:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  postgresdb3: