# docker-compose.yml
version: '3.8'

services:
  haproxy:
    image: myhaproxy
    container_name: haproxy
    ports:
      - "5000:5000"
      - "5001:5001"
      - "7000:7000"
      - "7001:7001"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./confd:/etc/confd
    environment:
      ETCD_URL: http://etcd:2379
