---

- name: Install on all servers
  hosts: manager_servers
  become: yes
  roles:
    - ../roles/common

- hosts: manager_servers
  become: yes
  roles:
    - ../roles/haproxy
    - ../roles/pgbouncer