---

# - name: Install docker on all servers
#   hosts: etcd_servers
#   become: yes
#   roles:
#     - ../roles/common

- hosts: etcd_servers
  become: yes
  roles:
    - ../roles/pgbouncer
    - ../roles/task-manager
