# Generated by Django 5.1.1 on 2024-09-06 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_namespace', models.CharField(blank=True, max_length=255, null=True)),
                ('node_list', models.TextField(null=True)),
                ('haproxy_info', models.TextField(null=True)),
                ('cluster_scope', models.CharField(max_length=255, unique=True)),
                ('config', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('username', models.CharField(default='hello', max_length=200)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('birthday', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node', models.CharField(max_length=255)),
                ('backup_type', models.CharField(choices=[('full', 'Full'), ('incremental', 'Incremental'), ('pitr', 'PITR')], max_length=12)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('backup_status', models.CharField(max_length=255)),
                ('backup_size', models.BigIntegerField()),
                ('backup_location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='base.cluster')),
            ],
        ),
        migrations.CreateModel(
            name='FailoverHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_leader', models.CharField(max_length=255)),
                ('new_leader', models.CharField(max_length=255)),
                ('event_type', models.CharField(choices=[('failover', 'Failover'), ('switchover', 'Switchover')], max_length=10)),
                ('initiated_by', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failover_history', to='base.cluster')),
            ],
        ),
    ]
