# Generated by Django 5.1.1 on 2024-09-09 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_full_name_customer_first_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='User',
        ),
        migrations.RemoveField(
            model_name='cluster',
            name='customer',
        ),
        migrations.AddField(
            model_name='cluster',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='base.user'),
        ),
    ]
