# Generated by Django 5.1.1 on 2024-09-09 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_customer_user_remove_cluster_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cluster',
            name='node_list',
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=50)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='base.cluster')),
            ],
        ),
        migrations.AlterField(
            model_name='backup',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='base.node'),
        ),
        migrations.AlterField(
            model_name='failoverhistory',
            name='new_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_leader_failovers', to='base.node'),
        ),
        migrations.AlterField(
            model_name='failoverhistory',
            name='old_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_leader_failovers', to='base.node'),
        ),
    ]
