# docker-compose.yml
version: '3.8'

services:
  haproxy:
    build: .
    container_name: haproxy
    ports:
      - "5000:5000"
      - "5001:5001"
      - "7000:7000"
      - "7001:7001"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./confd:/etc/confd
      - ./entrypoint.sh:/usr/local/bin/entrypoint.sh